/** 所有 repository 的统一出口 */
export { songsRepository } from './songs'
export type { NewSongRecord, SongPatch } from './songs'
export { assetsRepository } from './assets'
export type { NewScoreAssetRecord } from './assets'
export { sourceLinksRepository } from './sourceLinks'
export type { NewSourceLinkRecord } from './sourceLinks'
export { practiceSessionsRepository } from './practiceSessions'
export type { NewPracticeSessionRecord, FinishSessionInput } from './practiceSessions'
export { recordingsRepository } from './recordings'
export type { UpsertRecordingRecord } from './recordings'
export { resourceSourcesRepository } from './resourceSources'
export type { NewResourceSourceRecord, ResourceSourcePatch } from './resourceSources'
export { downloadJobsRepository } from './downloadJobs'
export type { NewDownloadJobRecord } from './downloadJobs'
export { settingsRepository, SETTINGS_KEY_APP } from './settings'
